name: all_academies
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  horizontal_calendar: ^1.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/documents/college-physics.pdf
    - assets/images/profile.jpg

  fonts:
    - family: Biotic
      fonts:
        - asset: assets/fonts/Fontspring-DEMO-biotic-regular.otf
        - asset: assets/fonts/Fontspring-DEMO-biotic-bold.otf
          weight: 700
        - asset: assets/fonts/Fontspring-DEMO-biotic-bolditalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-biotic-black.otf
          weight: 900
        - asset: assets/fonts/Fontspring-DEMO-biotic-blackitalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-biotic-extrabold.otf
          weight: 800
        - asset: assets/fonts/Fontspring-DEMO-biotic-extrabolditalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-biotic-extralight.otf
          weight: 200
        - asset: assets/fonts/Fontspring-DEMO-biotic-extralightitalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-biotic-italic.otf
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-biotic-light.otf
          weight: 300
        - asset: assets/fonts/Fontspring-DEMO-biotic-lightitalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-biotic-medium.otf
          weight: 500
        - asset: assets/fonts/Fontspring-DEMO-biotic-mediumitalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-biotic-semibold.otf
          weight: 600
        - asset: assets/fonts/Fontspring-DEMO-biotic-semibolditalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-biotic-thin.otf
          weight: 100
        - asset: assets/fonts/Fontspring-DEMO-biotic-thinitalic.otf
          weight: 100
          style: italic
